-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 15:02:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ltdeventos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ltdeventos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ltdeventos` DEFAULT CHARACTER SET utf8 ;
USE `ltdeventos` ;

-- -----------------------------------------------------
-- Table `ltdeventos`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ltdeventos`.`user` (
  `user_id` VARCHAR(36) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `matricula` VARCHAR(12) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `user_type` ENUM('professor', 'coordenador', 'aluno') NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `userId_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ltdeventos`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ltdeventos`.`local` (
  `local_id` VARCHAR(36) NOT NULL,
  `local_capacidade` INT UNSIGNED NOT NULL,
  `local_tipo` ENUM('campus', 'externo') NOT NULL,
  `local_endereco` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`local_id`),
  UNIQUE INDEX `localId_UNIQUE` (`local_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ltdeventos`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ltdeventos`.`evento` (
  `evento_id` VARCHAR(36) NOT NULL,
  `evento_nome` VARCHAR(255) NOT NULL,
  `evento_desc` TEXT NOT NULL,
  `evento_capacidade` INT UNSIGNED NOT NULL,
  `evento_inicio` TIMESTAMP NOT NULL,
  `evento_fim` TIMESTAMP NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `local_local_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NULL,
  PRIMARY KEY (`evento_id`, `local_local_id`),
  UNIQUE INDEX `eventoId_UNIQUE` (`evento_id` ASC) VISIBLE,
  INDEX `fk_evento_local_idx` (`local_local_id` ASC) VISIBLE,
  INDEX `fk_evento_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_evento_local`
    FOREIGN KEY (`local_local_id`)
    REFERENCES `ltdeventos`.`local` (`local_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ltdeventos`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
